### ISSUE TITLE
Handle headings with embedded links

### ISSUE THREAD

**Issue by nwiltsie** [uclahs-cds/tool-Nextflow-action#19]
[This heading](https://github.com/uclahs-cds/pipeline-call-mtSNV/tree/d46c4be37b4ab44db649c827a69af214bba4bf17?tab=readme-ov-file#please-see-list-of-contributors-at-github) caused the doc action to fail:

```python
Traceback (most recent call last):
  File "/src/action.py", line 349, in <module>
    run_action(ARGS.mkdocs_config, ARGS.readme)
  File "/src/action.py", line 293, in run_action
    config_file = create_mkdocs_config.build_mkdocs_config(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/create_mkdocs_config.py", line 334, in build_mkdocs_config
    readme_nav = split_readme(
                 ^^^^^^^^^^^^^
  File "/src/create_mkdocs_config.py", line 231, in split_readme
    token.attrs["href"] = sanitize_link(token.attrs["href"])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/create_mkdocs_config.py", line 217, in sanitize_link
    path=anchor_pages[get_heading_anchor(link.fragment)],
         ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'please-see-list-of-contributors-at-github'
```

https://github.com/uclahs-cds/pipeline-call-mtSNV/actions/runs/8177894254/job/22360585969

**Comment by yashpatel6** [comment]
That feels like a poorly formatted section though I guess the issue is with having links in the header?

**Comment by nwiltsie** [comment]
Yeah, it's any embedded markdown - GitHub is doing some further parsing that I didn't anticipate.
